import csv
import sys
import os
from pathlib import Path
from typing import Dict, Any, List, Set

# Add project root to path
sys.path.insert(0, str(Path(__file__).parent.parent.parent))

from src.connectors.supabase import SupabaseConnector
from src.utils.logging import setup_logging

# Setup logging
setup_logging()

def normalize_country_code(country: str) -> str:
    if not country:
        return "ZA"
    country = country.strip().upper()
    if country in ["SOUTH AFRICA", "ZA", "ZAF"]:
        return "ZA"
    return country

def import_filtered_suppliers():
    """Import suppliers from Address_Book.csv based on potential_suppliers.txt whitelist"""
    
    csv_path = Path(__file__).parent.parent.parent.parent / "Address_Book.csv"
    whitelist_path = Path(__file__).parent.parent.parent.parent / "potential_suppliers.txt"
    
    if not csv_path.exists():
        print(f"Error: Could not find {csv_path}")
        return
        
    if not whitelist_path.exists():
        print(f"Error: Could not find {whitelist_path}")
        return

    # Load whitelist
    print(f"Loading whitelist from {whitelist_path}...")
    whitelist: Set[str] = set()
    with open(whitelist_path, 'r', encoding='utf-8') as f:
        for line in f:
            line = line.strip()
            if line and not line.startswith('#'):
                whitelist.add(line)
                
    print(f"Found {len(whitelist)} suppliers in whitelist.")
    
    if not whitelist:
        print("Whitelist is empty. Nothing to import.")
        return

    connector = SupabaseConnector()
    
    print(f"Reading from {csv_path}...")
    
    imported_count = 0
    skipped_count = 0
    
    with open(csv_path, 'r', encoding='utf-8-sig') as f:
        # Skip metadata line if present
        first_line = f.readline()
        if "Generated by" not in first_line:
            f.seek(0)
            
        reader = csv.DictReader(f, delimiter=',')
        
        for row in reader:
            company_name = str(row.get('Company/Building / Floor / Unit') or '').strip()
            
            if company_name not in whitelist:
                continue
                
            # Prepare record
            record = {
                "name": company_name,
                "company": company_name,
                "street_address": str(row.get('Street address') or '').strip(),
                "local_area": str(row.get('Suburb') or '').strip(),
                "city": str(row.get('City') or '').strip(),
                "code": str(row.get('Postal code') or '').strip(),
                "country_code": normalize_country_code(str(row.get('Country') or '')),
                "contact_name": str(row.get('Contact name') or '').strip(),
                "contact_email": str(row.get('Contact email') or '').strip(),
                "contact_phone": str(row.get('Mobile number') or '').strip()
            }
            
            # Basic validation
            if not record['street_address'] or not record['city']:
                print(f"Skipping {company_name}: Missing address details")
                skipped_count += 1
                continue

            try:
                # Upsert into Supabase
                connector.client.table("supplier_addresses").upsert(
                    record, 
                    on_conflict="name"
                ).execute()
                
                print(f"Imported: {company_name}")
                imported_count += 1
                
            except Exception as e:
                print(f"Failed to import {company_name}: {e}")
                skipped_count += 1

    print(f"\nImport completed!")
    print(f"Imported: {imported_count}")
    print(f"Skipped: {skipped_count}")

if __name__ == "__main__":
    import_filtered_suppliers()
