import csv
import sys
from pathlib import Path

def list_potential_suppliers():
    """List all Business company names from Address_Book.csv to potential_suppliers.txt"""
    
    csv_path = Path(__file__).parent.parent.parent.parent / "Address_Book.csv"
    output_path = Path(__file__).parent.parent.parent.parent / "potential_suppliers.txt"
    
    if not csv_path.exists():
        print(f"Error: Could not find {csv_path}")
        return

    print(f"Reading from {csv_path}...")
    
    companies = set()
    
    with open(csv_path, 'r', encoding='utf-8-sig') as f:
        # Skip the first line if it's metadata (it looks like "Generated by...")
        first_line = f.readline()
        if "Generated by" not in first_line:
            f.seek(0)
            
        reader = csv.DictReader(f, delimiter=',')
        
        for row in reader:
            # Only look at Business addresses
            address_type = str(row.get('Address type') or '').strip().lower()
            if 'business' not in address_type:
                continue
                
            company_name = str(row.get('Company/Building / Floor / Unit') or '').strip()
            if company_name:
                companies.add(company_name)
    
    # Sort and write to file
    sorted_companies = sorted(list(companies))
    
    with open(output_path, 'w', encoding='utf-8') as f:
        f.write("# REVIEW THIS LIST: Delete lines for companies that are NOT suppliers.\n")
        f.write("# Save the file, and then I will import the remaining ones.\n\n")
        for company in sorted_companies:
            f.write(f"{company}\n")
            
    print(f"Found {len(sorted_companies)} potential suppliers.")
    print(f"Written to {output_path}")

if __name__ == "__main__":
    list_potential_suppliers()
