-- Create product_matches table for Alignment System
CREATE TABLE IF NOT EXISTS product_matches (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    internal_product_id UUID NOT NULL, -- Link to products.id (UUID)
    opencart_product_id BIGINT NOT NULL,
    match_type TEXT DEFAULT 'manual',
    score INTEGER DEFAULT 100,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    
    -- Ensure unique link per internal product? 
    -- Or unique per pair? For now, let's just index internal_product_id
    CONSTRAINT unique_match UNIQUE (internal_product_id, opencart_product_id)
);

CREATE INDEX IF NOT EXISTS idx_product_matches_internal ON product_matches(internal_product_id);
CREATE INDEX IF NOT EXISTS idx_product_matches_opencart ON product_matches(opencart_product_id);

-- Grant access
GRANT SELECT, INSERT, UPDATE, DELETE ON product_matches TO authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON product_matches TO anon;
GRANT USAGE, SELECT ON SEQUENCE product_matches_id_seq TO authenticated;
GRANT USAGE, SELECT ON SEQUENCE product_matches_id_seq TO anon;
